sudo: false
dist: trusty
language: node_js
node_js:
- "4"
- "6"
- "8"
- "stable"
os:
- linux
- osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install jq; fi
  - if [[ `node --version` ==  v6* ]]; then npm install -g npm; fi
install:
  - npm install --ignore-scripts
script:
  - npm run test

jobs:
  include:
    - stage: integration test
    - &integ-test
      install: npm install --only=dev --ignore-scripts
      script: npm run test-integration
      node_js: "4"
      os: 
      - linux
      - os x
    - <<: *integ-test
      node_js: "6"
    - <<: *integ-test
      node_js: "8"
    - <<: *integ-test
      node_js: "stable"
    - stage: npm release
      if: branch = master AND type = push
      node_js: "8"
      script: npm run-script build && npm run semantic-release
